apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgres-init.fullname" . }}
  labels:
    {{- include "postgres-init.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.job.annotations | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "postgres-init.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres-init.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: {{ tpl .Values.postgresql.host . | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.postgresql.existingSecret . }}
                  key: {{ tpl .Values.postgresql.existingSecretPostgresPasswordKey . }}

            - name: DB_NAME
              value: {{ tpl .Values.database.name . | quote }} 
            - name: DB_USER
              value: {{ tpl .Values.database.user . | quote }} 
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: {{ .Values.database.secret}} 
                  key: {{ .Values.database.secretUserPasswordKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
