{{- range .Values.databases }}
{{- if not .password -}}
{{- $secret := lookup "v1" "Secret" $.Release.Namespace (tpl .secret $) }}
{{- if not $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .secret $ | quote }}
  labels:
    {{- include "postgres-init.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ tpl .secretUserPasswordKey $ | quote }}: {{ randAlphaNum 10 | b64enc | quote }}
{{- end -}}
{{- end -}}
{{- end -}}

