{{- if not .Values.postgresql.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-init.fullname" . }}
  labels:
    {{- include "postgres-init.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  DB_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
{{- end -}}
