{{- if not .Values.database.password -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.database.secret }}
  {{- if $secret }}
    {{- if not (hasKey $secret.data .Values.database.secretUserPasswordKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret }}
  labels:
    {{- include "postgres-init.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  {{ tpl .Values.database.secretUserPasswordKey . | quote }}: {{ randAlphaNum 10 | b64enc | quote }}
    {{- end -}}
  {{- end -}}
{{- end -}}

